#! /bin/sh

# Visual options

bspc config top_padding             25
bspc config border_width            2
bspc config -m focused border_width 2
bspc config window_gap              5
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config click_to_focus          true
bspc config history_aware_focus     false
bspc config ignore_ewmh_focus       true
bspc config auto_cancel             true
bspc config auto_alternate          true
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side


## COLORS ##

bspc config focused_border_color            "#90969B"
bspc config normal_border_color             "#292825"
bspc config presel_border_color             "#C2AD9D"
bspc config focused_sticky_border_color     "#62712C"
bspc config normal_sticky_border_color      "#3D444E"
bspc config focused_private_border_color    "#9D534A"
bspc config normal_private_border_color     "#9B7046"


# Rules
#bspc rule -a Neovim     desktop=^2
bspc rule -a Nitrogen   state=floating
bspc rule -a Oblogout   layer=above focus=on monitor=1 state=fullscreen
#rm -f "$xwin_cache"

# Script files
HIDEFILE="/tmp/panel_mpris"
#echo 0 > $HIDEFILE

#source $HOME/Guit/PC/source.sh

# Gnome keyring
eval $(gnome-keyring-daemon --start)
eval `ssh-agent`
export SSH_AUTH_SOCK

# For lemonbuddy in my laptop
if [[ -e /tmp/bspwm_1_0-socket ]]; then
    ln -s /tmp/bspwm_1_0-socket /tmp/bspwm_0_0-socket
fi

xsetroot -cursor_name left_ptr &
sxhkd &
nitrogen --restore
setxkbmap es

i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
         -n "$i" \
         -d $i/{1,2,3,4}
    let i++
done

if [[ $(hostname) == 'dada-laptop' ]]; then
    polybar laptop &
    xinput set-prop "Elan Touchpad" "libinput Tapping Enabled" 1
elif [[ $(hostname) == 'VLSI-1' ]]; then
    bspc config -m 0x00200004 top_padding 0
    polybar vlsi &
elif [[ $(hostname) == 'dada-pc' ]]; then
    polybar home &
fi
